package com.qa.Exceptions;

public class Runner {

	public static void main(String[] args) {
		
		Maths maths = new Maths();
		Maths mathdiv = new Maths();
		
		maths.divide(6, 4);
		
		
		
		
		
		
//		try {
//		maths.multiply(6, 4);
//	} catch (MultiplyByFiveExc e) {
//		e.printStackTrace();
//		
//	}
//	}
}
